use std::{
    env, fs,
    path::{Path, PathBuf},
};

use anyhow::{anyhow, Context, Result};
use specta_typescript::Typescript;

/// Runs a module Specta exporter with shared CLI parsing and output formatting.
pub fn export_types<F>(module_label: &str, generator_name: Option<&str>, generate: F) -> Result<()>
where
    F: FnOnce(&Typescript) -> Result<Vec<String>>,
{
    let output_path = parse_output_path()?;
    let typescript = Typescript::default();
    let sections = generate(&typescript)?;
    let generator = generator_name.unwrap_or("common-modules");
    write_exports(&output_path, generator, &sections)?;
    println!(
        "[{module_label}] exported Specta types to {}",
        output_path.display()
    );
    Ok(())
}

fn write_exports(path: &Path, generator_name: &str, sections: &[String]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create directory for {}", parent.display()))?;
    }

    let file_contents = format!(
        "// @generated by {generator}. DO NOT EDIT.\n{}\n",
        sections.join("\n\n"),
        generator = generator_name
    );

    fs::write(path, file_contents)
        .with_context(|| format!("failed to write exported types to {}", path.display()))?;
    Ok(())
}

fn parse_output_path() -> Result<PathBuf> {
    let mut args = env::args().skip(1);
    let mut output_path: Option<PathBuf> = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--output" | "-o" => {
                let value = args
                    .next()
                    .ok_or_else(|| anyhow!("--output requires a file path"))?;
                output_path = Some(PathBuf::from(value));
            }
            other => {
                return Err(anyhow!("unrecognised argument: {other}"));
            }
        }
    }

    output_path.ok_or_else(|| anyhow!("missing required --output <path> argument"))
}
