// Mirror @openpcb/contracts AssistantSDK wire types. Single source of truth lives in shared/.
export type {
  AiContextBinding,
  AiContextBindingKind,
  AiContextBindingRole,
  AiContextBindingStatus,
  AiContextSizePreference,
  AiProviderCapabilities,
  AiProviderKind,
  AiSourceRef,
  AiToolStatus,
  AssistantChat,
  AssistantContextBindingDto,
  AssistantMessage,
  AssistantMessageMetadata,
  AssistantPromptPreset,
  AssistantPromptPresetId,
  AssistantProviderConfig,
  AssistantProviderConfigInput,
  AssistantProviderId,
  AssistantProviderKind,
  AssistantProviderModel,
  AssistantRole,
  AssistantSDK,
  AssistantSettings,
  AssistantToolCallSummary,
  AssistantToolEventDto,
  AssistantToolExecutionPolicy,
  CreateAssistantChatInput,
  ProviderTestResult,
  SubmitAssistantMessageInput,
  SubmitAssistantMessageResult,
} from "@openpcb/contracts";
