/**
 * The local Claude Code plugin marketplace OpenPCB generates — pure content,
 * no `electron` import, so Bun tests can check it (and run the skills' tool
 * names against the live MCP tool list).
 *
 * Layout written under `<userData>/claude-code/marketplace/`:
 *
 *   .claude-plugin/marketplace.json        name "openpcb-desktop"
 *   openpcb/.claude-plugin/plugin.json     version = the app's version
 *   openpcb/.mcp.json                      the MCP server entry (stdioServerConfig)
 *   openpcb/skills/<name>/SKILL.md         copied from the template shipped with the app
 *
 * Claude Code copies an installed plugin into its own cache, so what
 * `.mcp.json` names must stay valid across app updates. On macOS / Linux that
 * is the stable launcher the app rewrites every launch. On Windows it is the
 * app binary + ELECTRON_RUN_AS_NODE (no cmd.exe in the transport); when that
 * binary moves, the app sees the drift against its registration record and
 * Settings offers "Update plugin".
 */

export const MARKETPLACE_NAME = "openpcb-desktop";
export const PLUGIN_NAME = "openpcb";
export const MCP_SERVER_NAME = "openpcb";

export interface PluginBuildInput {
  appVersion: string;
  /** Template files, relative to the template's plugin root (e.g. "skills/x/SKILL.md"). */
  templateFiles: Record<string, string>;
  server: { command: string; args: string[]; env?: Record<string, string> };
}

/** Relative path → file contents for the whole marketplace directory. */
export function buildPluginMarketplace(input: PluginBuildInput): Record<string, string> {
  const files: Record<string, string> = {};
  files[".claude-plugin/marketplace.json"] = `${JSON.stringify(
    {
      name: MARKETPLACE_NAME,
      owner: { name: "OpenPCB" },
      description: "The OpenPCB desktop app's own Claude Code plugin, generated by the installed app.",
      plugins: [
        {
          name: PLUGIN_NAME,
          source: `./${PLUGIN_NAME}`,
          description:
            "Drive the OpenPCB desktop app from Claude Code: schematic, PCB and library tools plus build, review, DRC, BOM and layout workflows.",
          version: input.appVersion,
        },
      ],
    },
    null,
    2,
  )}\n`;
  files[`${PLUGIN_NAME}/.claude-plugin/plugin.json`] = `${JSON.stringify(
    {
      name: PLUGIN_NAME,
      version: input.appVersion,
      description:
        "Drive the OpenPCB desktop app from Claude Code: schematic, PCB and library tools plus build, review, DRC, BOM and layout workflows.",
      author: { name: "OpenPCB" },
    },
    null,
    2,
  )}\n`;
  files[`${PLUGIN_NAME}/.mcp.json`] = `${JSON.stringify(
    {
      mcpServers: {
        [MCP_SERVER_NAME]: {
          command: input.server.command,
          args: input.server.args,
          ...(input.server.env ? { env: input.server.env } : {}),
        },
      },
    },
    null,
    2,
  )}\n`;
  for (const [relative, contents] of Object.entries(input.templateFiles)) {
    // The template README is for repo readers; plugin.json/.mcp.json are generated.
    if (relative === "README.md") continue;
    files[`${PLUGIN_NAME}/${relative}`] = contents;
  }
  return files;
}

/** Every MCP tool name a skill mentions (backticked snake_case identifiers). */
export function toolNamesInSkill(markdown: string): string[] {
  const names = new Set<string>();
  for (const match of markdown.matchAll(/`((?:designer|library|pcb|assistant|knowledge)_[a-z_]+|compile_circuit)`/g)) {
    names.add(match[1]!);
  }
  return [...names];
}
