#!/usr/bin/env bun

/**
 * Module SDK Generator
 *
 * Generates TypeScript SDKs from module manifests and bridge introspection.
 * Creates typed service interfaces and HTTP/WS client wrappers per module.
 */
import { spawnSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), "..");
const MODULES_DIR = path.join(ROOT, "modules");
const SDK_OUTPUT_DIR = path.join(ROOT, "src-react", "src", "generated", "sdk");
const MANIFESTS_FILE = path.join(ROOT, "src-react", "src", "generated", "modules.ts");
const INTROSPECT_BIN = path.join(ROOT, "target", "debug", "bridge-introspect");

// =============================================================================
// Types
// =============================================================================

interface ModuleManifest {
  id: string;
  namespace: string;
  label: string;
  version: string;
  kind: string;
  exports: {
    services: Array<{
      id: string;
      kind: string;
      description?: string;
    }>;
    widgets: string[];
  };
}

interface BridgeCommand {
  name: string;
  args_rust: string;
  result_rust: string;
  stream: boolean;
  long?: boolean;
}

interface BridgeModule {
  namespace: string;
  commands: BridgeCommand[];
  events: Array<{
    name: string;
    payload_rust: string;
  }>;
}

interface BridgeManifest {
  modules: BridgeModule[];
}

// =============================================================================
// Manifest Loading
// =============================================================================

async function loadModuleManifests(): Promise<ModuleManifest[]> {
  const manifests: ModuleManifest[] = [];

  const entries = await fs.readdir(MODULES_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith("_")) {
      continue;
    }

    const manifestPath = path.join(MODULES_DIR, entry.name, "manifest.json");
    try {
      const raw = await fs.readFile(manifestPath, "utf8");
      const parsed = JSON.parse(raw);

      manifests.push({
        id: parsed.id,
        namespace: parsed.namespace,
        label: parsed.label,
        version: parsed.version,
        kind: parsed.kind ?? "space",
        exports: {
          services: parsed.exports?.services ?? [],
          widgets: parsed.exports?.widgets ?? [],
        },
      });
    } catch {
      // Skip modules without manifest
    }
  }

  return manifests;
}

function loadBridgeManifest(): BridgeManifest {
  const binPath = process.platform === "win32" ? `${INTROSPECT_BIN}.exe` : INTROSPECT_BIN;
  const run = spawnSync(binPath, [], {
    encoding: "utf8",
    cwd: ROOT,
  });

  if (run.status !== 0) {
    console.warn("[gen-sdk] Bridge introspect failed, using empty manifest");
    return { modules: [] };
  }

  try {
    return JSON.parse(run.stdout);
  } catch {
    console.warn("[gen-sdk] Failed to parse bridge manifest");
    return { modules: [] };
  }
}

// =============================================================================
// SDK Generation
// =============================================================================

function sanitizeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function toPascalCase(str: string): string {
  return str
    .split(/[._-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function generateModuleSDK(
  manifest: ModuleManifest,
  bridgeModule: BridgeModule | undefined,
): string {
  const sdkName = `${toPascalCase(manifest.id)}SDK`;
  const lines: string[] = [];

  // Header
  lines.push(`// @generated by scripts/gen-sdk.ts. DO NOT EDIT.`);
  lines.push(`// SDK for module: ${manifest.id} (${manifest.namespace})`);
  lines.push(``);

  // Only import ModuleContext if there are bridge commands
  if (bridgeModule && bridgeModule.commands.length > 0) {
    lines.push(`import type { ModuleContext } from "@/modules/ModuleContext";`);
    lines.push(``);
  }

  // Module info
  lines.push(`// =============================================================================`);
  lines.push(`// Module Info`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  lines.push(`export const MODULE_ID = "${manifest.id}" as const;`);
  lines.push(`export const MODULE_NAMESPACE = "${manifest.namespace}" as const;`);
  lines.push(`export const MODULE_VERSION = "${manifest.version}" as const;`);
  lines.push(`export const MODULE_KIND = "${manifest.kind}" as const;`);
  lines.push(``);

  // Service interface (if module exports services)
  if (manifest.exports.services.length > 0) {
    lines.push(`// =============================================================================`);
    lines.push(`// Service Interface`);
    lines.push(`// =============================================================================`);
    lines.push(``);
    lines.push(`/**`);
    lines.push(` * Service interface for ${manifest.label}`);
    lines.push(` * These services are exported by this module and can be used by other modules.`);
    lines.push(` */`);
    lines.push(`export interface ${sdkName}Services {`);

    for (const service of manifest.exports.services) {
      const methodName = sanitizeIdentifier(service.id.split(".").pop() ?? service.id);
      const description = service.description ?? `Service: ${service.id}`;
      lines.push(`  /** ${description} (${service.kind}) */`);
      lines.push(`  ${methodName}: unknown;`);
    }

    lines.push(`}`);
    lines.push(``);
  }

  // Bridge client interface (if module has bridge commands)
  if (bridgeModule && bridgeModule.commands.length > 0) {
    lines.push(`// =============================================================================`);
    lines.push(`// Bridge Client Interface`);
    lines.push(`// =============================================================================`);
    lines.push(``);
    lines.push(`/**`);
    lines.push(` * Typed bridge client for ${manifest.label}`);
    lines.push(` * Use this to call Rust commands from this module.`);
    lines.push(` */`);
    lines.push(`export interface ${sdkName}BridgeClient {`);

    for (const cmd of bridgeModule.commands) {
      lines.push(`  /** Bridge command: ${cmd.name} */`);
      lines.push(`  ${cmd.name}(args?: unknown): Promise<unknown>;`);
    }

    lines.push(`}`);
    lines.push(``);

    // Bridge client factory
    lines.push(`/**`);
    lines.push(` * Create a typed bridge client for this module`);
    lines.push(` */`);
    lines.push(`export function createBridgeClient(ctx: ModuleContext): ${sdkName}BridgeClient {`);
    lines.push(`  return {`);

    for (const cmd of bridgeModule.commands) {
      lines.push(`    ${cmd.name}: (args) => ctx.bridge.invoke("${bridgeModule.namespace}", "${cmd.name}", args),`);
    }

    lines.push(`  };`);
    lines.push(`}`);
    lines.push(``);
  }

  // HTTP SDK interface (for modules that expose HTTP endpoints)
  lines.push(`// =============================================================================`);
  lines.push(`// HTTP SDK Interface`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  lines.push(`/** HTTP base path for this module */`);
  lines.push(`export const HTTP_BASE_PATH = "/api/modules/${manifest.id}" as const;`);
  lines.push(``);
  lines.push(`/** WebSocket base path for this module */`);
  lines.push(`export const WS_BASE_PATH = "/ws/modules/${manifest.id}" as const;`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * HTTP SDK for ${manifest.label}`);
  lines.push(` * Use this to call HTTP endpoints exposed by this module.`);
  lines.push(` */`);
  lines.push(`export interface ${sdkName}HttpClient {`);
  lines.push(`  /** Make a GET request to this module's API */`);
  lines.push(`  get<T>(path: string, options?: RequestInit): Promise<T>;`);
  lines.push(`  /** Make a POST request to this module's API */`);
  lines.push(`  post<T>(path: string, body?: unknown, options?: RequestInit): Promise<T>;`);
  lines.push(`  /** Make a PUT request to this module's API */`);
  lines.push(`  put<T>(path: string, body?: unknown, options?: RequestInit): Promise<T>;`);
  lines.push(`  /** Make a DELETE request to this module's API */`);
  lines.push(`  delete<T>(path: string, options?: RequestInit): Promise<T>;`);
  lines.push(`}`);
  lines.push(``);

  // HTTP client factory
  lines.push(`/**`);
  lines.push(` * Create an HTTP client for this module`);
  lines.push(` */`);
  lines.push(`export function createHttpClient(baseUrl?: string): ${sdkName}HttpClient {`);
  lines.push(`  const base = baseUrl ?? HTTP_BASE_PATH;`);
  lines.push(``);
  lines.push(`  async function request<T>(method: string, path: string, body?: unknown, options?: RequestInit): Promise<T> {`);
  lines.push(`    const url = \`\${base}\${path}\`;`);
  lines.push(`    const init: RequestInit = {`);
  lines.push(`      method,`);
  lines.push(`      headers: { "Content-Type": "application/json", ...options?.headers },`);
  lines.push(`      ...options,`);
  lines.push(`    };`);
  lines.push(`    if (body !== undefined) {`);
  lines.push(`      init.body = JSON.stringify(body);`);
  lines.push(`    }`);
  lines.push(`    const response = await fetch(url, init);`);
  lines.push(`    if (!response.ok) {`);
  lines.push(`      throw new Error(\`HTTP \${response.status}: \${response.statusText}\`);`);
  lines.push(`    }`);
  lines.push(`    return response.json();`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  return {`);
  lines.push(`    get: (path, options) => request("GET", path, undefined, options),`);
  lines.push(`    post: (path, body, options) => request("POST", path, body, options),`);
  lines.push(`    put: (path, body, options) => request("PUT", path, body, options),`);
  lines.push(`    delete: (path, options) => request("DELETE", path, undefined, options),`);
  lines.push(`  };`);
  lines.push(`}`);
  lines.push(``);

  // Combined SDK
  lines.push(`// =============================================================================`);
  lines.push(`// Combined SDK`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Full SDK for ${manifest.label}`);
  lines.push(` * Provides access to all module capabilities.`);
  lines.push(` */`);
  lines.push(`export interface ${sdkName} {`);
  lines.push(`  readonly moduleId: typeof MODULE_ID;`);
  lines.push(`  readonly namespace: typeof MODULE_NAMESPACE;`);
  lines.push(`  readonly version: typeof MODULE_VERSION;`);
  lines.push(`  readonly http: ${sdkName}HttpClient;`);

  if (bridgeModule && bridgeModule.commands.length > 0) {
    lines.push(`  readonly bridge: ${sdkName}BridgeClient;`);
  }

  lines.push(`}`);
  lines.push(``);

  // SDK factory
  lines.push(`/**`);
  lines.push(` * Create the full SDK for this module`);
  lines.push(` */`);
  lines.push(`export function createSDK(`);

  if (bridgeModule && bridgeModule.commands.length > 0) {
    lines.push(`  ctx?: ModuleContext,`);
  }

  lines.push(`  options?: { httpBaseUrl?: string },`);
  lines.push(`): ${sdkName} {`);
  lines.push(`  return {`);
  lines.push(`    moduleId: MODULE_ID,`);
  lines.push(`    namespace: MODULE_NAMESPACE,`);
  lines.push(`    version: MODULE_VERSION,`);
  lines.push(`    http: createHttpClient(options?.httpBaseUrl),`);

  if (bridgeModule && bridgeModule.commands.length > 0) {
    lines.push(`    bridge: ctx ? createBridgeClient(ctx) : (undefined as never),`);
  }

  lines.push(`  };`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function generateIndexFile(manifests: ModuleManifest[]): string {
  const lines: string[] = [];

  lines.push(`// @generated by scripts/gen-sdk.ts. DO NOT EDIT.`);
  lines.push(`// SDK index - re-exports all module SDKs`);
  lines.push(``);

  for (const manifest of manifests) {
    const fileName = manifest.id.replace(/[^a-zA-Z0-9]/g, "-");
    lines.push(`export * as ${sanitizeIdentifier(manifest.id)} from "./${fileName}";`);
  }

  lines.push(``);

  return lines.join("\n");
}

// =============================================================================
// Main
// =============================================================================

async function main() {
  console.log("[gen-sdk] Starting SDK generation...");

  // Load manifests
  const manifests = await loadModuleManifests();
  console.log(`[gen-sdk] Found ${manifests.length} module(s)`);

  if (manifests.length === 0) {
    console.log("[gen-sdk] No modules found, skipping SDK generation");
    return;
  }

  // Load bridge manifest
  const bridgeManifest = loadBridgeManifest();
  const bridgeByNamespace = new Map(
    bridgeManifest.modules.map((m) => [m.namespace, m]),
  );

  // Ensure output directory exists
  await fs.mkdir(SDK_OUTPUT_DIR, { recursive: true });

  // Generate SDK for each module
  for (const manifest of manifests) {
    const bridgeModule = bridgeByNamespace.get(manifest.namespace);
    const sdk = generateModuleSDK(manifest, bridgeModule);

    const fileName = manifest.id.replace(/[^a-zA-Z0-9]/g, "-") + ".ts";
    const outputPath = path.join(SDK_OUTPUT_DIR, fileName);
    await fs.writeFile(outputPath, sdk, "utf8");

    console.log(`[gen-sdk] Generated SDK: ${fileName}`);
  }

  // Generate index file
  const indexContent = generateIndexFile(manifests);
  const indexPath = path.join(SDK_OUTPUT_DIR, "index.ts");
  await fs.writeFile(indexPath, indexContent, "utf8");

  console.log(`[gen-sdk] Generated index file`);
  console.log(`[gen-sdk] Done! Generated ${manifests.length} SDK(s)`);
}

main().catch((error) => {
  console.error("[gen-sdk] Error:", error);
  process.exit(1);
});
