#!/usr/bin/env bun

import { performance } from "node:perf_hooks";
import { spawn } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

interface ModuleManifest {
    id: string;
    namespace?: string;
}

interface ModuleTarget {
    id: string;
    namespace: string;
    cargoManifest: string;
}
//@ts-ignore
const __filename = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(__filename), "..");
const coreManifestPath = path.join(repoRoot, "src-tauri", "Cargo.toml");
const tauriBindingsPath = path.join(repoRoot, "src-ts", "core", "generated", "tauri-bindings.ts");
const generatedDir = path.join(repoRoot, "src-ts", "core", "generated", "types");
const generatedIndexPath = path.join(generatedDir, "index.ts");
const coreTypesFile = path.join(generatedDir, "core.ts");
const modulesDir = path.join(repoRoot, "modules");

function log(message: string): void {
    console.log(`[gen-types] ${message}`);
}

async function runCargo(args: string[], label: string): Promise<void> {
    log(`running cargo ${label}`);
    await new Promise<void>((resolve, reject) => {
        const child = spawn("cargo", args, {
            cwd: repoRoot,
            stdio: "inherit",
        });

        child.on("exit", (code) => {
            if (code === 0) {
                resolve();
            } else {
                reject(new Error(`cargo ${label} exited with code ${code}`));
            }
        });
        child.on("error", (error) => reject(error));
    });
}

async function ensureGeneratedTree(): Promise<void> {
    await fs.mkdir(generatedDir, { recursive: true });
}

function toPosix(value: string): string {
    return value.split(path.sep).join(path.posix.sep);
}

async function exportCoreTypes(): Promise<void> {
    await runCargo([
        "run",
        "--manifest-path",
        coreManifestPath,
        "--bin",
        "export_bindings",
    ], "export_bindings");

    // Post-process tauri-bindings.ts to add @ts-nocheck for unused variables in generated code
    const bindingsContent = await fs.readFile(tauriBindingsPath, "utf8");
    if (!bindingsContent.startsWith("// @ts-nocheck")) {
        await fs.writeFile(tauriBindingsPath, `// @ts-nocheck\n${bindingsContent}`, "utf8");
    }

    const relativeImport = (() => {
        const relPath = path.relative(path.dirname(coreTypesFile), tauriBindingsPath);
        const normalized = relPath.startsWith(".") ? relPath : `./${relPath}`;
        const withoutExtension = normalized.replace(/\.(ts|tsx|js|jsx)$/, "");
        return toPosix(withoutExtension);
    })();

    const content = `// @generated by scripts/gen-types.ts. DO NOT EDIT.\nexport * from "${relativeImport}";\n`;
    await fs.writeFile(coreTypesFile, content, "utf8");
}

async function discoverModuleTargets(): Promise<ModuleTarget[]> {
    const entries = await fs.readdir(modulesDir, { withFileTypes: true }).catch((error) => {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") {
            log("modules directory not found, skipping module Specta exports");
            return [];
        }
        throw error;
    });

    const targets: ModuleTarget[] = [];

    for (const entry of entries) {
        if (!entry.isDirectory()) {
            continue;
        }

        const moduleRoot = path.join(modulesDir, entry.name);
        const manifestPath = path.join(moduleRoot, "manifest.json");
        const rustManifest = path.join(moduleRoot, "rust", "Cargo.toml");

        try {
            const [manifestRaw] = await Promise.all([
                fs.readFile(manifestPath, "utf8"),
                fs.access(rustManifest),
            ]);
            const manifest = JSON.parse(manifestRaw) as ModuleManifest;
            if (!manifest.id) {
                console.warn(`[gen-types] skipping ${entry.name} – manifest missing id`);
                continue;
            }

            targets.push({
                id: manifest.id,
                namespace: manifest.namespace ?? `space.${manifest.id}`,
                cargoManifest: rustManifest,
            });
        } catch (error) {
            const errno = (error as NodeJS.ErrnoException).code;
            if (errno === "ENOENT") {
                console.warn(
                    `[gen-types] skipping ${entry.name} – missing manifest or rust/Cargo.toml`,
                );
                continue;
            }
            throw error;
        }
    }

    targets.sort((a, b) => a.id.localeCompare(b.id));
    return targets;
}

async function exportModuleTypes(targets: ModuleTarget[]): Promise<string[]> {
    const generatedModules: string[] = [];

    for (const target of targets) {
        const outputFile = path.join(generatedDir, `module-${target.id}.ts`);
        await runCargo(
            [
                "run",
                "--manifest-path",
                target.cargoManifest,
                "--bin",
                "export_types",
                "--",
                "--output",
                outputFile,
            ],
            `export_types (${target.id})`,
        );
        generatedModules.push(target.id);
    }

    return generatedModules;
}

async function writeGeneratedIndex(modules: string[]): Promise<void> {
    const lines = ["export * from \"./core\";"];
    for (const moduleId of modules) {
        lines.push(`export * from \"./module-${moduleId}\";`);
    }

    const content = `// @generated by scripts/gen-types.ts. DO NOT EDIT.\n${lines.join("\n")}\n`;
    await fs.writeFile(generatedIndexPath, content, "utf8");
}

// No separate public index needed - types are exported from generatedDir directly

async function main(): Promise<void> {
    const start = performance.now();
    await ensureGeneratedTree();
    await exportCoreTypes();
    const modules = await discoverModuleTargets();
    const generatedModules = await exportModuleTypes(modules);
    await writeGeneratedIndex(generatedModules);
    const durationMs = (performance.now() - start).toFixed(0);
    log(`exported core types and ${generatedModules.length} module type file(s) in ${durationMs}ms`);
}

main().catch((error) => {
    console.error("[gen-types] failed", error);
    process.exitCode = 1;
});
