/**
 * Message Schema
 *
 * Messages in a chat with full branching support for conversations.
 * Supports tree structure with parent-child relationships and active paths.
 *
 * Enhanced for AI Task Management System:
 * - taskId links assistant messages to their generating task
 * - provider field tracks which provider generated the message
 *
 * See: TASK_SYSTEM_SPECIFICATION.md
 */

import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";
import { uuidPrimaryKey, timestamps, softDelete } from "./base";
import { chat } from "./chat";
import { task } from "./task";

export const message = sqliteTable(
  "message",
  {
    ...uuidPrimaryKey,
    chatId: text("chat_id")
      .notNull()
      .references(() => chat.id, { onDelete: "cascade" }),
    parentMessageId: text("parent_message_id").references((): any => message.id, {
      onDelete: "cascade",
    }),
    role: text("role", { enum: ["system", "user", "assistant", "tool"] }).notNull(),
    content: text("content", { mode: "json" }).notNull().$type<MessageContent>(),

    // Task linkage (for assistant messages generated by MessageTask)
    taskId: text("task_id").references(() => task.id, { onDelete: "set null" }),

    // Provider context (for assistant messages)
    provider: text("provider"), // AI provider that generated this message
    model: text("model"), // Model used for assistant messages

    // Token usage (more detailed than TokenCount)
    tokenCount: text("token_count", { mode: "json" }).$type<TokenCount>(),
    tokens: text("tokens", { mode: "json" }).$type<MessageTokens>(), // Spec-compliant tokens

    // Branching support
    branchIndex: integer("branch_index").notNull().default(0), // Order among siblings
    depth: integer("depth").notNull().default(0), // Tree depth (0 = root)
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), // Active branch path

    // Generation params
    generationParams: text("generation_params", { mode: "json" }).$type<GenerationParams>(),

    // Metadata for incomplete/cancelled messages
    metadata: text("metadata", { mode: "json" }).$type<MessageMetadata>(),

    ...timestamps,
    ...softDelete,
  },
  (table) => ({
    chatIdx: index("idx_message_chat").on(table.chatId),
    parentIdx: index("idx_message_parent").on(table.parentMessageId),
    activePathIdx: index("idx_message_active_path").on(
      table.chatId,
      table.isActive,
      table.depth
    ),
    branchIdx: index("idx_message_branch").on(table.parentMessageId, table.branchIndex),
    taskIdx: index("idx_message_task").on(table.taskId),
    chatCreatedIdx: index("idx_message_chat_created").on(table.chatId, table.createdAt),
  })
);

export type Message = typeof message.$inferSelect;
export type NewMessage = typeof message.$inferInsert;

/**
 * Token usage for a message
 */
export interface TokenCount {
  input: number;
  output: number;
}

/**
 * Generation parameters used for AI responses
 */
export interface GenerationParams {
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  [key: string]: unknown;
}

/**
 * Message content supports various types matching modern AI chat interfaces
 */
export interface MessageContent {
  type: "text" | "tool_call" | "tool_result" | "multipart";

  // For type="text"
  text?: string;

  // For type="tool_call"
  toolCalls?: ToolCall[];

  // For type="tool_result"
  toolCallId?: string;
  toolResult?: unknown;
  isError?: boolean;

  // For type="multipart"
  parts?: ContentPart[];
}

export interface ToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

export interface ContentPart {
  type: "text" | "image" | "file" | "code" | "reasoning";
  text?: string;
  imageData?: string; // base64 for small images
  /** @deprecated Use fileId instead. Will be removed in future version. */
  fileReferenceId?: string; // reference for large files (deprecated)
  /** Reference to file in unified file system */
  fileId?: string; // reference to file table
  altText?: string;
  code?: string;
  language?: string;
}

/**
 * Token usage following spec format (prompt, completion, total)
 */
export interface MessageTokens {
  prompt?: number;
  completion?: number;
  total?: number;
}

/**
 * Message metadata for incomplete/cancelled messages
 */
export interface MessageMetadata {
  incomplete?: boolean; // If generation was interrupted
  cancelled?: boolean; // If user cancelled
  error?: string; // If generation failed
  customFields?: Record<string, unknown>;
}
